"""Offline, GT-assisted pixel reachability of an existing logit correction.

For each pixel independently, this diagnostic relaxes a proposed residual gain
to the closed interval [0, 2]: z(a) = z_o3 + a * (z_v1 - z_o3). It gives an
optimistic pixel-IoU ceiling under that relaxed family, not a Pd/Fa bound, a
learnability result, an inference rule, or a deployable trained model. Callers
must restrict labels to their authorized source-training diagnostic scope.

The closed interval is a relaxation of an open tanh gain range; in particular,
a false positive removable only at a zero-valued endpoint may not be removable
inside the open interval. Classification here is strictly float64 logit > 0,
not an assertion of bit-exact equivalence with finite-precision GPU sigmoid.
"""

from __future__ import annotations

from typing import Any

import numpy as np


def _floating_logits(value: Any, name: str) -> np.ndarray:
    array = np.asarray(value)
    if array.size == 0:
        raise ValueError(f"{name} must be nonempty")
    if not np.issubdtype(array.dtype, np.floating):
        raise TypeError(f"{name} must contain floating-point logits")
    if not np.isfinite(array).all():
        raise ValueError(f"{name} must be finite")
    try:
        with np.errstate(over="raise", invalid="raise"):
            result = np.array(array, dtype=np.float64, copy=True)
    except FloatingPointError as exc:
        raise ValueError(f"{name} must be representable as finite float64") from exc
    if not np.isfinite(result).all():
        raise ValueError(f"{name} must be representable as finite float64")
    return result


def _binary_target(value: Any, shape: tuple[int, ...]) -> np.ndarray:
    array = np.asarray(value)
    if array.shape != shape or array.size == 0:
        raise ValueError("target must have the same nonempty shape as both logits")
    if not (np.issubdtype(array.dtype, np.bool_) or np.issubdtype(array.dtype, np.integer)
            or np.issubdtype(array.dtype, np.floating)):
        raise TypeError("target must contain binary numeric or boolean GT")
    if not np.isfinite(array).all() or not np.logical_or(array == 0, array == 1).all():
        raise ValueError("target must contain finite binary GT")
    return np.array(array, dtype=np.bool_, copy=True)


def _count(value: np.ndarray) -> int:
    return int(np.count_nonzero(value))


def _iou(tp: int, fp: int, fn: int) -> float:
    union = tp + fp + fn
    # Same empty-union convention as the repository's pixel evaluator.
    return float(tp / union) if union else 1.0


def analyze_reachability(z_o3: Any, z_v1: Any, target: Any) -> dict[str, Any]:
    """Return ``{'counts': JSON-safe dict, 'arrays': NumPy array dict}``.

    Inputs have any identical nonempty shape, including a zero-dimensional
    NumPy scalar. Logits must have floating dtype; binary GT may also be bool
    or integer. All arithmetic is float64 and all mask arrays are np.bool_.
    Finite inputs whose extrapolated endpoint overflows float64 are rejected.

    ``oracle_gain`` starts at 1 and changes only repairable v1 FN/FP pixels to
    0 or 2. Its mask is generated by selecting the exact original z_o3/z_v1
    or computed z2 endpoint, avoiding a second, differently rounded evaluation
    of the affine expression at a=1. Ties at zero always classify as negative.
    """
    z0 = _floating_logits(z_o3, "z_o3")
    z1 = _floating_logits(z_v1, "z_v1")
    if z0.shape != z1.shape:
        raise ValueError("z_o3 and z_v1 must have identical shape")
    truth = _binary_target(target, z0.shape)
    with np.errstate(over="ignore", invalid="ignore"):
        z2 = 2.0 * z1 - z0
        # Preserve the requested expression's ordinary rounding, but do not
        # reject a finite endpoint merely because the temporary 2*z1 overflows
        # (for example an identity correction z0 == z1 == 1e308).
        if not np.isfinite(z2).all():
            stable_endpoint = z1 + (z1 - z0)
            z2 = np.where(np.isfinite(z2), z2, stable_endpoint)
    if not np.isfinite(z2).all():
        raise ValueError("extrapolated endpoint z2 must be finite float64")
    lower = np.minimum(z0, z2)
    upper = np.maximum(z0, z2)
    can_positive = upper > 0
    can_negative = lower <= 0
    v1_mask = z1 > 0
    v1_fn = truth & ~v1_mask
    v1_fp = ~truth & v1_mask
    repairable_fn = v1_fn & can_positive
    repairable_fp = v1_fp & can_negative
    unrepairable_fn = v1_fn & ~can_positive
    unrepairable_fp = v1_fp & ~can_negative
    oracle_mask = np.where(truth, can_positive, ~can_negative)

    gain = np.ones(z0.shape, dtype=np.float64)
    gain = np.where(repairable_fn, np.where(z2 > z0, 2.0, 0.0), gain)
    gain = np.where(repairable_fp, np.where(z2 < z0, 2.0, 0.0), gain)
    oracle_logit = np.where(gain == 0, z0, np.where(gain == 2, z2, z1))
    if not np.array_equal(oracle_logit > 0, oracle_mask):
        raise RuntimeError("chosen endpoint gains do not reproduce the oracle mask")

    v1_tp = _count(truth & v1_mask)
    oracle_tp = _count(truth & oracle_mask)
    oracle_fp = _count(~truth & oracle_mask)
    oracle_fn = _count(truth & ~oracle_mask)
    counts = {
        "pixels": int(z0.size),
        "gt_positive_pixels": _count(truth),
        "gt_negative_pixels": _count(~truth),
        "v1_tp": v1_tp,
        "v1_fp": _count(v1_fp),
        "v1_fn": _count(v1_fn),
        "repairable_fn": _count(repairable_fn),
        "repairable_fp": _count(repairable_fp),
        "unrepairable_fn": _count(unrepairable_fn),
        "unrepairable_fp": _count(unrepairable_fp),
        "oracle_tp": oracle_tp,
        "oracle_fp": oracle_fp,
        "oracle_fn": oracle_fn,
        "v1_iou": _iou(v1_tp, _count(v1_fp), _count(v1_fn)),
        "oracle_iou": _iou(oracle_tp, oracle_fp, oracle_fn),
        "zero_logit_counts": {"z_o3": _count(z0 == 0), "z_v1": _count(z1 == 0),
                              "z2": _count(z2 == 0), "lower": _count(lower == 0),
                              "upper": _count(upper == 0)},
        "repairable_fp_only_at_zero_endpoint": _count(repairable_fp & (lower == 0)),
        "oracle_gain_counts": {"0": _count(gain == 0), "1": _count(gain == 1), "2": _count(gain == 2)},
    }
    arrays = {
        "oracle_mask": oracle_mask,
        "can_positive": can_positive,
        "can_negative": can_negative,
        "v1_false_negative": v1_fn,
        "v1_false_positive": v1_fp,
        "repairable_fn": repairable_fn,
        "repairable_fp": repairable_fp,
        "unrepairable_fn": unrepairable_fn,
        "unrepairable_fp": unrepairable_fp,
        "lower_logit": lower,
        "upper_logit": upper,
        "oracle_gain": gain,
    }
    # np.asarray preserves scalar-shaped outputs as arrays rather than np.bool_.
    return {"counts": counts, "arrays": {name: np.asarray(value) for name, value in arrays.items()}}


__all__ = ["analyze_reachability"]
